In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
df =  pd.read_csv('yellow_tripdata_2021-01.csv', nrows=100)

In [4]:
df

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01T00:30:10.000,2021-01-01T00:36:12.000,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01T00:51:20.000,2021-01-01T00:52:19.000,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01T00:43:30.000,2021-01-01T01:11:06.000,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01T00:15:48.000,2021-01-01T00:31:01.000,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01T00:31:49.000,2021-01-01T00:48:21.000,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2021-01-01T00:12:41.000,2021-01-01T00:26:47.000,1,4.13,1,N,161,226,1,14.5,0.5,0.5,3.66,0.0,0.3,21.96,2.5
96,2,2021-01-01T00:23:29.000,2021-01-01T00:35:03.000,2,4.12,1,N,162,74,2,13.5,0.5,0.5,0.00,0.0,0.3,17.30,2.5
97,2,2021-01-01T00:46:17.000,2021-01-01T00:54:25.000,2,2.22,1,N,144,170,1,9.0,0.5,0.5,2.56,0.0,0.3,15.36,2.5
98,2,2021-01-01T00:28:16.000,2021-01-01T00:51:44.000,1,7.11,1,N,264,264,2,23.5,0.5,0.5,0.00,0.0,0.3,24.80,0.0
99,2,2021-01-01T00:42:35.000,2021-01-01T00:54:41.000,3,1.61,1,N,229,237,2,9.5,0.5,0.5,0.00,0.0,0.3,13.30,2.5

In [6]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data'))

CREATE TABLE "yellow_taxi_data" (
"vendorid" INTEGER,
  "tpep_pickup_datetime" TEXT,
  "tpep_dropoff_datetime" TEXT,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "ratecodeid" INTEGER,
  "store_and_fwd_flag" TEXT,
  "pulocationid" INTEGER,
  "dolocationid" INTEGER,
  "payment_type" INTEGER,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "congestion_surcharge" REAL
)

In [7]:
pd.to_datetime(df.tpep_pickup_datetime)

0    2021-01-01 00:30:10
1    2021-01-01 00:51:20
2    2021-01-01 00:43:30
3    2021-01-01 00:15:48
4    2021-01-01 00:31:49
             ...
95   2021-01-01 00:12:41
96   2021-01-01 00:23:29
97   2021-01-01 00:46:17
98   2021-01-01 00:28:16
99   2021-01-01 00:42:35
Name: tpep_pickup_datetime, Length: 100, dtype: datetime64[ns]

In [8]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [18]:
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	vendorid BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	ratecodeid BIGINT,
	store_and_fwd_flag TEXT,
	pulocationid BIGINT,
	dolocationid BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [10]:
from sqlalchemy import create_engine

In [11]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

ModuleNotFoundError: No module named 'psycopg2'

In [12]:
import psycopg2

ModuleNotFoundError: No module named 'psycopg2'

In [13]:
import psycopg2

ModuleNotFoundError: No module named 'psycopg2'

In [14]:
pip install psycopg2

Collecting psycopg2
  Using cached psycopg2-2.9.11.tar.gz (379 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /private/var/folders/xj/bps591_15jb0br708h2br3y40000gn/T/pip-build-env-h0a33fv3/overlay/lib/python3.14/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      running egg_info
      writing psycopg2.egg-info/PKG-INFO
      writing dependency_links to psycopg2.egg-info/dependency_links.txt
      writing top-level names to psycopg2.egg-info/top_level.txt

      Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'psycopg2' when getting requirements to build wheel
Note: you may need to restart the kernel to use updated packages.

In [15]:
pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.

In [16]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [17]:
engine

Engine(postgresql://root:***@localhost:5432/ny_taxi)

In [19]:
df_iter = pd.read_csv('yellow_tripdata_2021-01.csv', iterator=True, chunksize=1000)

In [20]:
df = next(df_iter)

In [21]:
len(df)

1000

In [22]:
df.head(n=1)

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01T00:30:10.000,2021-01-01T00:36:12.000,1,2.1,1,N,142,43,2,8.0,3.0,0.5,0.0,0.0,0.3,11.8,2.5

In [23]:
df.head(n=0)

Empty DataFrame
Columns: [vendorid, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, ratecodeid, store_and_fwd_flag, pulocationid, dolocationid, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [24]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=Engine, if_exists='replace')

NameError: name 'Engine' is not defined

In [25]:
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [26]:
df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

1000